name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure CMake with tests
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run GTest via CTest
        run: |
          cd build
          ctest --output-on-failure

      - name: Build Docker image
        run: docker build -t print-demo .

      - name: Test Docker container with volume and stdin
        run: |
          mkdir -p /tmp/print-logs

          printf "Hello\nfrom\nDocker\n" | docker run --rm \
            -e LOG_PATH=/logs/log.txt \
            -v /tmp/print-logs:/logs \
            -i print-demo

          EXPECTED_CONTENT="Hello\nfrom\nDocker"
          ACTUAL_CONTENT=$(cat /tmp/print-logs/log.txt)

          if [ "$ACTUAL_CONTENT" != "$EXPECTED_CONTENT" ]; then
            echo "Log content mismatch!"
            echo "Expected:"
            echo "$EXPECTED_CONTENT"
            echo "Actual:"
            echo "$ACTUAL_CONTENT"
            exit 1
          fi

          echo "Container works correctly: logs saved to host volume."
