name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure CMake with tests
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run GTest via CTest
        run: |
          cd build
          ctest --output-on-failure

      - name: Build Docker image
        run: docker build -t print-demo .

      - name: Test Docker container with volume and stdin
        run: |
          mkdir -p /tmp/print-logs

          printf "Hello\nfrom\nDocker\n" | docker run --rm \
            -e LOG_PATH=/logs/log.txt \
            -v /tmp/print-logs:/logs \
            -i print-demo

          printf "Hello\nfrom\nDocker\n" > /tmp/expected.txt

          if diff /tmp/expected.txt /tmp/print-logs/log.txt; then
            echo "Container works correctly: logs saved to host volume."
          else
            echo "Log content mismatch!"
            exit 1
          fi



          
